### ISSUE TITLE
vue-press error

### ISSUE THREAD

**Issue by danny1144** [meteorlxy/vssue-demo#2]
vue.runtime.esm.js?2b0e:619 [Vue warn]: Unknown custom element: <Vssue> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <V14e5519c> at vuepress/README.md
       <Content>
         <Page> at node_modules/@vuepress/theme-default/components/Page.vue
           <Layout> at node_modules/@vuepress/theme-default/layouts/Layout.vue
             <GlobalLayout> at node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue
               <Root>

**Comment by meteorlxy** [comment]
提供的信息过少，不知道是什么问题。

这边更新了一下 demo 的依赖，可以 pull 一下重新安装依赖试试

**Comment by danny1144** [comment]
好的，已经好了。谢谢、 @meteorlxy
